[package]
name = "private_event_sourcing_types"
version = "0.1.0"
edition = "2021"

[dependencies]
hdk = { workspace = true }
holochain_serialized_bytes = { workspace = true }
serde = { workspace = true }
